@startuml
class AAUOC {
    newLocation(l : Location) : void
    newEvent(e : Event) : void
    newPerson(p : Person) : void
    informEvent(e : Event) : void
    register(m : Member,e : Event) : void
}
class Person{
    name : String
}
class Member{
    e-mail : String
}
class BoardMember{}
class Event{
    date : Date
    description : String

    assign(l : Location) : void
}
class Conference{
    max_attendees : Integer
}
class BoardMeeting{}
class Location{
    description : String
    address : String
}

AAUOC o-- Person
AAUOC o-- Event
AAUOC o-- Location
Event <|-- BoardMeeting
Event <|-- Conference
Member <|-- BoardMember
Person <|-- Member

Location --Event : isLocatedIn
Event -- Member : attendsTo
Conference -- Person :attendsTo
BoardMember -- BoardMeeting : attendsTo


@enduml